name: Go

on:
  push:
    branches: [ modular-test ]
  pull_request:
    branches: [ modular-test ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: GO111MODULE="auto" go test -v ./task4
  build:

    runs-on: ubuntu-latest
    needs: [test] # Only run this workflow when "test" workflow succeeds
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./task4/ --file ./task4/Dockerfile --tag timelordfang/mockapi:$(date +%s)
    #- name: Push Image
      #run: docker login ;docker push ...

